keep-open=yes					# не выходить из mpv после окончания файла
volume=100                 # стандартная громкость

hwdec=auto-safe            # Включить безопасное аппаратное ускорение видео
vo=gpu-next                # Рендеринг через современный видеовыход
# gpu-api=vulkan             # Использовать Vulkan при наличии
profile=gpu-hq             # Высокое качество рендеринга

osd-on-seek=msg-bar
osd-duration=1000

# Скриншоты
screenshot-directory=~/Pictures/screenshots
screenshot-format=png
screenshot-template="%f_%tY%tm%td_%tH%tM%tS"
